version: 2
updates:
  - package-ecosystem: "gradle"
    # path to build.gradle
    directory: "/"
    schedule:
      interval: "daily"
    ignored_updates:
      - match:
          dependency_name: "forge"
