package com.mndk.bteterrarenderer.connector.graphics;

public enum VertexFormatConnectorEnum {
    BLOCK,
    ITEM,
    OLDMODEL_POSITION_TEX_NORMAL,
    PARTICLE_POSITION_TEX_COLOR_LMAP,
    POSITION,
    POSITION_COLOR,
    POSITION_TEX,
    POSITION_NORMAL,
    POSITION_TEX_COLOR,
    POSITION_TEX_NORMAL,
    POSITION_TEX_LMAP_COLOR,
    POSITION_TEX_COLOR_NORMAL
}
