# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up JDK 1.21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Update git submodules
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: gitSubmoduleUpdate

      - name: Build core with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: buildNonModProjects

      - name: Build subprojects with Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: copyBuildResultToRoot

      - uses: actions/upload-artifact@v4
        with:
          name: Build result
          path: build/libs/*.jar